-- SAVIS developer control plane foundation
create table if not exists public.developer_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.developer_admins enable row level security;

create or replace function public.is_developer_admin()
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(select 1 from public.developer_admins where user_id=auth.uid());
$$;
grant execute on function public.is_developer_admin() to authenticated;

create table if not exists public.developer_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.developer_audit_log enable row level security;

create or replace function public.write_developer_audit(p_action text, p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_developer_admin() then raise exception 'developer access required'; end if;
  insert into public.developer_audit_log(actor_id,action,metadata) values(auth.uid(),p_action,coalesce(p_metadata,'{}'::jsonb));
end $$;
grant execute on function public.write_developer_audit(text,jsonb) to authenticated;

create table if not exists public.feature_flags (
  key text primary key,
  enabled boolean not null default false,
  description text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.feature_flags enable row level security;

create or replace function public.list_developer_feature_flags()
returns setof public.feature_flags
language sql stable security definer set search_path=public
as $$ select * from public.feature_flags where public.is_developer_admin() order by key $$;
grant execute on function public.list_developer_feature_flags() to authenticated;

create or replace function public.set_developer_feature_flag(p_key text,p_enabled boolean,p_description text default null)
returns public.feature_flags
language plpgsql security definer set search_path=public
as $$
declare r public.feature_flags;
begin
  if not public.is_developer_admin() then raise exception 'developer access required'; end if;
  insert into public.feature_flags(key,enabled,description,updated_by) values(p_key,p_enabled,p_description,auth.uid())
  on conflict(key) do update set enabled=excluded.enabled,description=coalesce(excluded.description,public.feature_flags.description),updated_by=auth.uid(),updated_at=now()
  returning * into r;
  perform public.write_developer_audit('feature_flag.update',jsonb_build_object('key',p_key,'enabled',p_enabled));
  return r;
end $$;
grant execute on function public.set_developer_feature_flag(text,boolean,text) to authenticated;


create or replace function public.list_developer_audit(p_limit integer default 50)
returns setof public.developer_audit_log
language sql stable security definer set search_path=public
as $$
  select * from public.developer_audit_log
  where public.is_developer_admin()
  order by created_at desc
  limit greatest(1, least(coalesce(p_limit,50),200))
$$;
grant execute on function public.list_developer_audit(integer) to authenticated;
