"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Mode = "safe" | "operational" | "nuclear";
type State = { maintenance_mode:boolean; read_only_mode:boolean; signup_enabled:boolean; payments_enabled:boolean; session_epoch:number };
const business = [["Providers","/dev-console-9f3k/business"],["Shops & Sellers","/dev-console-9f3k/business"],["Professionals","/dev-console-9f3k/business"],["Agents","/dev-console-9f3k/agents"]];
const operational = [["Business Control Center","/dev-console-9f3k/business"],["Assisted Sessions","/dev-console-9f3k/business"],["Agent Management","/dev-console-9f3k/agents"],["Marketplace","/dev-console-9f3k/operations"],["Bookings & Payments","/dev-console-9f3k/operations"],["Messaging","/dev-console-9f3k/operations"]];

export default function DeveloperConsole(){
 const db=useMemo(()=>createClient(),[]);
 const [allowed,setAllowed]=useState<boolean|null>(null),[email,setEmail]=useState("Developer"),[mode,setMode]=useState<Mode>("safe");
 const [flags,setFlags]=useState<any[]>([]),[key,setKey]=useState(""),[desc,setDesc]=useState(""),[state,setState]=useState<State|null>(null),[health,setHealth]=useState<any>(null),[audit,setAudit]=useState<any[]>([]);
 const [busy,setBusy]=useState(false),[bootstrap,setBootstrap]=useState(false),[nuclear,setNuclear]=useState(false),[code,setCode]=useState(""),[confirm,setConfirm]=useState(""),[action,setAction]=useState(""),[message,setMessage]=useState("");

 async function loadSafe(){const [{data:f},{data:s},{data:h},{data:a}]=await Promise.all([db.rpc("list_developer_feature_flags"),db.rpc("developer_security_snapshot"),db.rpc("developer_health_snapshot"),db.rpc("list_developer_audit",{p_limit:40})]);setFlags(f||[]);setState(s||null);setHealth(h||null);setAudit(a||[]);}
 useEffect(()=>{void(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){location.href="/login?next=/dev-console-9f3k";return}setEmail(user.email||"Developer");const {data}=await db.rpc("is_developer_admin");setAllowed(Boolean(data));if(data){await db.rpc("write_developer_audit",{p_action:"developer.console.open",p_metadata:{path:"/dev-console-9f3k"}});await loadSafe();}})()},[db]);
 async function bootstrapDeveloper(){setBootstrap(true);setMessage("");const r=await fetch("/api/developer/bootstrap",{method:"POST"});const j=await r.json();setBootstrap(false);setMessage(j.error||"Developer access provisioned. Refreshing…");if(r.ok)setTimeout(()=>location.reload(),500);}
 async function flag(k:string,on:boolean,d?:string){setBusy(true);const {data,error}=await db.rpc("set_developer_feature_flag",{p_key:k,p_enabled:on,p_description:d||null});setBusy(false);if(error){setMessage(error.message);return}setFlags(x=>[...x.filter(f=>f.key!==k),data].sort((a,b)=>a.key.localeCompare(b.key)));}
 async function security(){setBusy(true);setMessage("");const r=await fetch("/api/developer/security",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,action,confirmation:confirm})});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||"Control failed.");return}setState(j.state);setMessage("Emergency control applied and audited.");setCode("");setConfirm("");setAction("");}

 if(allowed===null)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white">Checking developer access…</main>;
 if(!allowed)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white"><div className="max-w-lg rounded-3xl border border-amber-400/20 bg-white/[.04] p-8 text-center"><p className="text-[11px] font-black uppercase tracking-[.25em] text-[#F5C451]">SAVIS Developer Control Plane</p><h1 className="mt-2 text-2xl font-black">Developer access is not provisioned</h1><p className="mt-3 text-sm leading-6 text-white/60">The console is deliberately allowlist protected. If this is the owner account, set the server-only SAVIS_DEVELOPER_EMAIL to this login email and keep the Supabase service-role key server-only, then use the one-time bootstrap below.</p><button disabled={bootstrap} onClick={()=>void bootstrapDeveloper()} className="mt-5 rounded-full bg-[#F5C451] px-5 py-3 text-sm font-black text-black">{bootstrap?"Provisioning…":"Provision this developer account"}</button>{message&&<p className="mt-3 text-xs text-white/50">{message}</p>}<Link href="/consumer" className="mt-4 block text-xs text-white/40">Exit</Link></div></main>;

 const cards=mode==="safe"?[["Overview","Health snapshot, environment state and current developer session."],["Analytics","Platform counts and operational visibility."],["Provider Review","Human KYC review remains reviewer-gated."],["Search & Location","Radius, category and simulated-city diagnostics."],["Feature Flags","Server-side switches with audit trail."],["Logs & Health","Recent developer audit events and health checks."]]:mode==="operational"?operational:[["Maintenance","Emergency marketplace controls require second authentication."],["Signup & Payments","Emergency entry-point switches require second authentication."],["Force Re-login","Session invalidation is isolated for the final auth integration."],["Data Operations","Irreversible database actions are intentionally not exposed from ordinary developer access."]];

 return <main className="min-h-screen bg-[#07050d] text-white">
 <header className="sticky top-0 z-30 border-b border-violet-400/15 bg-[#0b0714]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4"><div><p className="text-[11px] font-black uppercase tracking-[.25em] text-[#F5C451]">SAVIS Internal • Control Plane</p><h1 className="text-2xl font-black">Developer Console</h1></div><div className="flex items-center gap-2"><span className="hidden rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-2 text-xs text-violet-200 sm:inline">{email}</span><Link href="/consumer" className="rounded-full border border-white/15 px-4 py-2 text-xs font-black">Exit Developer Mode</Link></div></div></header>
 <div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 lg:grid-cols-[230px_1fr]">
 <aside className="h-fit rounded-3xl border border-violet-400/15 bg-white/[.035] p-3"><p className="px-3 pb-2 text-[10px] font-black uppercase tracking-[.2em] text-white/40">Control levels</p>{(["safe","operational","nuclear"] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} className={"mb-2 w-full rounded-2xl px-3 py-3 text-left text-sm font-black "+(mode===x?(x==="safe"?"bg-emerald-400/15 text-emerald-300":x==="operational"?"bg-amber-400/15 text-amber-300":"bg-red-500/15 text-red-300"):"text-white/60 hover:bg-white/5")}>{x==="safe"?"🟢":x==="operational"?"🟠":"🔴"} {x}</button>)}<div className="my-4 border-t border-white/10"/><p className="px-3 text-[10px] font-black uppercase tracking-[.2em] text-white/40">Business</p>{business.map(([t,h])=><Link key={t} href={h} className="mt-1 block rounded-xl px-3 py-2 text-sm text-white/65 hover:bg-white/5">{t}</Link>)}</aside>
 <section>
 <div className={"rounded-3xl border p-5 "+(mode==="safe"?"border-emerald-400/20 bg-emerald-400/[.035]":mode==="operational"?"border-amber-400/20 bg-amber-400/[.035]":"border-red-500/25 bg-red-500/[.035]")}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] opacity-60">{mode} control level</p><h2 className="mt-1 text-xl font-black">{mode==="safe"?"Observe & configure":mode==="operational"?"Operate with guardrails":"Second-authenticated emergency controls"}</h2></div>{mode==="nuclear"&&<button onClick={()=>setNuclear(!nuclear)} className="rounded-full bg-red-500 px-4 py-2 text-xs font-black">{nuclear?"Lock controls":"Authenticate controls"}</button>}</div><p className="mt-2 text-sm text-white/60">Developer actions never require business-owner passwords. Consumers are excluded from Business Control Center management.</p></div>
 <div className="mt-5 grid gap-4 md:grid-cols-2">{cards.map(([t,d])=><article key={t} className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex justify-between gap-3"><h3 className="font-black">{t}</h3><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-white/40">{mode}</span></div><p className="mt-2 text-sm leading-6 text-white/55">{d}</p>{mode==="operational"&&<Link href={t==="Business Control Center"||t==="Assisted Sessions"?"/dev-console-9f3k/business":t==="Agent Management"?"/dev-console-9f3k/agents":"/dev-console-9f3k/operations"} className="mt-4 inline-flex rounded-full border border-violet-300/20 bg-violet-300/10 px-4 py-2 text-xs font-black text-violet-200">Open {t}</Link>}</article>)}</div>
 {mode==="safe"&&<div className="mt-5 grid gap-5 lg:grid-cols-2">
 <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black">System health</h2><div className="mt-3 grid grid-cols-2 gap-2">{health&&Object.entries(health).map(([k,v])=><div key={k} className="rounded-2xl border border-white/8 bg-black/15 p-3"><p className="text-[10px] uppercase text-white/35">{k}</p><p className="mt-1 text-lg font-black">{String(v)}</p></div>)}</div><div className="mt-3 text-xs text-white/45">Maintenance: {state?.maintenance_mode?"ON":"OFF"} · Signup: {state?.signup_enabled?"ON":"OFF"} · Payments: {state?.payments_enabled?"ON":"OFF"} · Epoch: {state?.session_epoch??"—"}</div></section>
 <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black">Feature flags</h2><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={key} onChange={e=>setKey(e.target.value)} placeholder="flag_key" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"/><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="description" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"/><button disabled={busy||!key.trim()} onClick={()=>{void flag(key.trim(),false,desc.trim());setKey("");setDesc("")}} className="rounded-xl bg-[#F5C451] px-4 py-2 text-sm font-black text-black">Add</button></div><div className="mt-3 space-y-2">{flags.map(f=><div key={f.key} className="flex items-center justify-between rounded-2xl border border-white/8 p-3"><div><p className="text-sm font-bold">{f.key}</p><p className="text-xs text-white/40">{f.description||"No description"}</p></div><button onClick={()=>void flag(f.key,!f.enabled,f.description)} className={"rounded-full px-3 py-1.5 text-xs font-black "+(f.enabled?"bg-emerald-400/15 text-emerald-300":"bg-white/10 text-white/50")}>{f.enabled?"ON":"OFF"}</button></div>)}</div></section>
 <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5 lg:col-span-2"><h2 className="font-black">Audit trail</h2><div className="mt-3 max-h-72 space-y-2 overflow-auto">{audit.map(x=><div key={x.id} className="flex justify-between gap-4 rounded-xl border border-white/8 p-3 text-xs"><span className="font-bold">{x.action}</span><span className="text-white/35">{new Date(x.created_at).toLocaleString()}</span></div>)}</div></section></div>}
 {mode==="nuclear"&&nuclear&&<section className="mt-5 rounded-3xl border border-red-500/25 bg-red-500/[.05] p-5"><h2 className="font-black text-red-200">Second authentication</h2><p className="mt-2 text-sm text-white/55">Use the owner/developer-controlled 12-digit credential stored only as a server environment variable. Never paste it into chat or commit it.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,12))} placeholder="12-digit credential" inputMode="numeric" className="rounded-xl border border-red-400/20 bg-black/30 px-3 py-3"/><select value={action} onChange={e=>setAction(e.target.value)} className="rounded-xl border border-red-400/20 bg-black/30 px-3 py-3"><option value="">Choose control</option><option value="maintenance_on">Enable maintenance</option><option value="maintenance_off">Disable maintenance</option><option value="signup_off">Disable signup</option><option value="signup_on">Enable signup</option><option value="payments_off">Disable payments</option><option value="payments_on">Enable payments</option></select><input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder={action?"Type "+action.toUpperCase():"Typed confirmation"} className="rounded-xl border border-red-400/20 bg-black/30 px-3 py-3"/></div><button disabled={busy||!code||!action||!confirm} onClick={()=>void security()} className="mt-3 rounded-xl bg-red-500 px-5 py-3 text-sm font-black disabled:opacity-30">Apply emergency control</button>{message&&<p className="mt-3 text-xs text-white/60">{message}</p>}<p className="mt-4 text-[11px] leading-5 text-red-100/50">Irreversible data destruction is deliberately not exposed from this web console. Any future destructive workflow must remain separately authenticated, audited and explicitly enabled by the application owner.</p></section>}
 </section></div></main>
}