"use client";

import { useEffect, useState } from "react";
import { useRouter, useParams } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import Logo from "@/components/Logo";
import Button from "@/components/Button";
import { addBooking } from "@/lib/bookings";
import { getBalance, holdForJob } from "@/lib/wallet";
import { getSavedLocation, distanceKm } from "@/lib/location";

type Provider={id:string;name:string;skill:string;area:string;km:number;rate:number;rating:number;reviews:number;icon:string;available:string;bio:string;latitude?:number;longitude?:number;verified?:boolean};
const SAMPLE:Record<string,Provider>={
"1":{id:"1",name:"James Otieno",skill:"Plumbing",area:"Westlands",km:1.2,rate:1500,rating:4.9,reviews:87,icon:"🔧",available:"Available today",bio:"Experienced plumber with 8 years in Nairobi. Fast response for leaks, installations and tank work.",latitude:-1.2676,longitude:36.8108,verified:true},
"2":{id:"2",name:"Peter Kamau",skill:"Masonry",area:"Kilimani",km:2.4,rate:2000,rating:4.7,reviews:42,icon:"🧱",available:"This week",bio:"Reliable mason for walls, floors and small builds. Clean work and honest pricing.",latitude:-1.2921,longitude:36.7876,verified:true},
"3":{id:"3",name:"Grace Wanjiku",skill:"Tailoring",area:"Parklands",km:.8,rate:800,rating:5,reviews:63,icon:"✂️",available:"Available now",bio:"Custom dresses, alterations and school uniforms. Same-week turnaround for most jobs.",latitude:-1.258,longitude:36.817,verified:true},
"4":{id:"4",name:"Brian Mutua",skill:"Electrical",area:"Ruaka",km:3.1,rate:1800,rating:4.8,reviews:54,icon:"⚡",available:"Available today",bio:"Licensed electrician for homes and small businesses. Safe wiring and quick fault finding.",latitude:-1.2046,longitude:36.776,verified:true},
"5":{id:"5",name:"Amina Hassan",skill:"Cleaning",area:"Eastleigh",km:1.9,rate:1200,rating:4.6,reviews:31,icon:"🧹",available:"Available now",bio:"Deep cleaning, move-in/out and regular home cleaning. Reliable and thorough.",latitude:-1.276,longitude:36.85,verified:true},
"6":{id:"6",name:"Samuel Kiptoo",skill:"Carpentry",area:"Kasarani",km:4.2,rate:2500,rating:4.5,reviews:28,icon:"🪚",available:"This week",bio:"Furniture repairs, doors, shelves and custom woodwork.",latitude:-1.2218,longitude:36.897,verified:true},
"7":{id:"7",name:"Lucy Njeri",skill:"Painting",area:"Westlands",km:1.5,rate:1600,rating:4.9,reviews:39,icon:"🎨",available:"Available today",bio:"Interior and exterior painting. Neat finish and careful preparation.",latitude:-1.2676,longitude:36.8108,verified:true},
"8":{id:"8",name:"David Ochieng",skill:"Photography",area:"Kilimani",km:2,rate:3000,rating:4.8,reviews:71,icon:"📷",available:"This week",bio:"Events, portraits and product photos. Natural style and fast delivery.",latitude:-1.2921,longitude:36.7876,verified:true}};
const ICONS:Record<string,string>={Plumbing:"🔧",Masonry:"🧱",Electrical:"⚡",Tailoring:"✂️",Cleaning:"🧹",Carpentry:"🪚",Painting:"🎨",Photography:"📷"};
function rowToProvider(row:Record<string,unknown>):Provider{const skill=String(row.service_category||"General help");return{id:String(row.id),name:String(row.full_name||"SAVIS provider"),skill,area:String(row.location_name||"Nearby"),km:Number(row.distance_km)||0,rate:Number(row.hourly_rate)||0,rating:Number(row.rating)||0,reviews:Number(row.review_count)||0,icon:ICONS[skill]||"🛠️",available:String(row.availability||"Available"),bio:String(row.bio||"A local SAVIS provider ready to help."),latitude:row.latitude==null?undefined:Number(row.latitude),longitude:row.longitude==null?undefined:Number(row.longitude),verified:Boolean(row.verified)}}

export default function ProviderDetailPage(){
const router=useRouter(),params=useParams(),id=String(params.id||"");
const [provider,setProvider]=useState<Provider|null>(SAMPLE[id]||null),[loading,setLoading]=useState(true),[showForm,setShowForm]=useState(false),[desc,setDesc]=useState(""),[location,setLocation]=useState(""),[urgency,setUrgency]=useState("today"),[sent,setSent]=useState(false),[error,setError]=useState(""),[balance,setBalance]=useState(0);
useEffect(()=>{async function load(){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}setBalance(getBalance());if(!SAMPLE[id]){const {data}=await supabase.from("profiles").select("id,full_name,role,latitude,longitude,location_name,service_category,hourly_rate,rating,review_count,availability,verified,bio").eq("id",id).maybeSingle();if(data){const current=getSavedLocation();setProvider(rowToProvider({...data,distance_km:current&&data.latitude!=null&&data.longitude!=null?distanceKm(current,{latitude:Number(data.latitude),longitude:Number(data.longitude)}):0}))}}setLoading(false)}load()},[id,router]);
async function handleSend(e:React.FormEvent){e.preventDefault();setError("");if(!provider)return;if(desc.trim().length<5)return setError("Please describe the job in a few words.");if(!location.trim())return setError("Please add the job location.");const hold=holdForJob(provider.rate,"pending",`Hold for ${provider.name}`);if(!hold.ok)return setError(hold.message+" Top up from Profile (sample).");setBalance(getBalance());try{const current=getSavedLocation();await addBooking({providerId:id,providerName:provider.name,skill:provider.skill,description:desc.trim(),location:location.trim(),urgency,rate:provider.rate,latitude:current?.latitude,longitude:current?.longitude,locationAccuracy:current?.accuracy});setSent(true)}catch{setError("Could not send request. Please try again.")}}
if(loading)return <main className="min-h-screen flex items-center justify-center"><p className="text-[#B9C3C9]">Loading provider…</p></main>;
if(!provider)return <main className="min-h-screen bg-[#182126] flex flex-col items-center justify-center px-4 text-center"><p className="text-[#B9C3C9] mb-4">This provider is not available yet.</p><Link href="/consumer"><Button>Back to Home</Button></Link></main>;
if(sent)return <main className="min-h-screen bg-[#182126] flex flex-col items-center justify-center px-4"><div className="w-full max-w-md text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#34D399]/10 text-3xl">✓</div><h1 className="mt-5 text-2xl font-black">Request sent</h1><p className="mt-2 text-sm leading-6 text-[#B9C3C9]">Your request was sent to <strong className="text-white">{provider.name}</strong>.</p><p className="mt-2 text-xs text-[#65737A]">Wallet escrow is currently a prototype. No real M-Pesa charge has been made.</p><Link href="/consumer" className="mt-7 block"><Button full>Back to Home</Button></Link><Link href="/bookings" className="mt-3 block"><Button variant="outline" full>View my bookings</Button></Link></div></main>;
return <main className="min-h-screen bg-[#182126] pb-10">
<header className="sticky top-0 z-30 border-b border-white/10 bg-[#182126]/90 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-2xl items-center justify-between"><Link href="/consumer" aria-label="Back to SAVIS home"><Logo size="sm"/></Link><Link href="/consumer" className="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-[#D1D8DC]">← Back</Link></div></header>
<div className="mx-auto max-w-2xl px-4 pt-5">
<section className="overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-[#3b0809] via-[#252f35] to-[#1d272d] p-5 shadow-xl">
<div className="flex gap-4"><div className="relative flex h-20 w-20 shrink-0 items-center justify-center rounded-[24px] bg-gradient-to-br from-[#6C0102] to-[#C7080C] text-4xl shadow-lg">{provider.icon}{provider.verified!==false&&<span className="absolute -bottom-1 -right-1 flex h-6 w-6 items-center justify-center rounded-full border-2 border-[#252f35] bg-[#34D399] text-xs font-black text-[#06281c]">✓</span>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black tracking-tight">{provider.name}</h1>{provider.verified!==false&&<span className="rounded-full bg-[#34D399]/10 px-2 py-1 text-[.62rem] font-black text-[#67E8B1]">Verified</span>}</div><p className="mt-1 text-sm font-medium text-[#D1D8DC]">{provider.skill} · {provider.area}</p><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-[#B9C3C9]"><span>★ <b className="text-white">{provider.rating?provider.rating.toFixed(1):"New"}</b>{provider.reviews? ` · ${provider.reviews} reviews`:""}</span><span>📍 {provider.km.toFixed(1)} km away</span></div></div></div>
<div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#F5C451]/10 px-3 py-1.5 text-xs font-black text-[#F5C451]">{provider.rate?`From KSh ${provider.rate.toLocaleString()}`:"Rate on request"}</span><span className="rounded-full bg-white/8 px-3 py-1.5 text-xs font-bold text-[#D1D8DC]">{provider.available}</span><span className="rounded-full bg-white/8 px-3 py-1.5 text-xs font-bold text-[#D1D8DC]">M-Pesa</span></div>
</section>
<section className="mt-4 rounded-[22px] border border-white/10 bg-[#222b31]/75 p-5"><h2 className="text-base font-black">About this provider</h2><p className="mt-2 text-sm leading-6 text-[#B9C3C9]">{provider.bio}</p></section>
<section className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-[20px] border border-white/10 bg-[#222b31]/75 p-4"><p className="text-lg font-black">{provider.rating?provider.rating.toFixed(1):"New"}</p><p className="mt-1 text-[.68rem] text-[#849198]">Customer rating</p></div><div className="rounded-[20px] border border-white/10 bg-[#222b31]/75 p-4"><p className="text-lg font-black">{provider.reviews||0}</p><p className="mt-1 text-[.68rem] text-[#849198]">Reviews</p></div><div className="rounded-[20px] border border-white/10 bg-[#222b31]/75 p-4"><p className="text-lg font-black">{provider.km.toFixed(1)} km</p><p className="mt-1 text-[.68rem] text-[#849198]">From you</p></div></section>
<section className="mt-4 rounded-[22px] border border-white/10 bg-[#222b31]/75 p-5"><h2 className="font-black">Service area</h2><p className="mt-2 text-sm leading-6 text-[#B9C3C9]">Usually serves {provider.area}. Your exact location is only used when you explicitly enable location.</p></section>
<div className="mt-5 sticky bottom-3 z-20 rounded-[22px] border border-white/10 bg-[#182126]/90 p-2 backdrop-blur-xl">
{!showForm?<div className="grid grid-cols-2 gap-2"><Button full onClick={()=>setShowForm(true)}>Request a quote</Button><Button variant="outline" full onClick={()=>setShowForm(true)}>Book now</Button></div>:<form onSubmit={handleSend} className="space-y-4 p-2"><div><h2 className="font-black text-lg">Request service</h2><p className="mt-1 text-xs text-[#849198]">Tell {provider.name} what you need.</p></div><div><label className="mb-1.5 block text-xs font-bold text-[#B9C3C9]">Describe the job</label><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={3} className="w-full resize-none rounded-2xl border border-white/15 bg-black/35 px-4 py-3 text-sm outline-none focus:border-[#E22227]" placeholder="e.g. Kitchen sink is leaking under the pipe"/></div><div><label className="mb-1.5 block text-xs font-bold text-[#B9C3C9]">Job location</label><input value={location} onChange={e=>setLocation(e.target.value)} className="w-full rounded-2xl border border-white/15 bg-black/35 px-4 py-3.5 text-sm outline-none focus:border-[#E22227]" placeholder="e.g. Westlands, near Sarit Centre"/></div><div><label className="mb-1.5 block text-xs font-bold text-[#B9C3C9]">How soon?</label><select value={urgency} onChange={e=>setUrgency(e.target.value)} className="w-full rounded-2xl border border-white/15 bg-black/35 px-4 py-3.5 text-sm outline-none focus:border-[#E22227]"><option value="now">Right now</option><option value="today">Today</option><option value="week">This week</option></select></div><div className="rounded-2xl border border-[#F5C451]/25 bg-[#F5C451]/8 p-3"><p className="text-xs font-black text-[#F5C451]">SAVIS Wallet · prototype</p><p className="mt-1 text-xs leading-5 text-[#B9C3C9]">KSh {provider.rate.toLocaleString()} is the current sample hold amount. No real M-Pesa payment is made.</p></div>{error&&<p className="text-sm font-semibold text-[#ff8a8d]">{error}</p>}<Button type="submit" full>Send request</Button><button type="button" onClick={()=>setShowForm(false)} className="w-full py-2 text-sm text-[#B9C3C9]">Cancel</button></form>}
</div></div></main>;
}