"use client";
import {useEffect,useState} from "react"; import Link from "next/link"; import {createClient} from "@/lib/supabase/client"; import {normalizeKenyanPhone} from "@/lib/mpesa-phone";
type Job={id:string;status:string;quoted_amount:number|null}; type Payment={id:string;amount:number;status:string;mpesa_receipt:string|null;result_desc:string|null};
export default function ConsumerPaymentsPage(){
 const [jobs,setJobs]=useState<Job[]>([]),[payments,setPayments]=useState<Payment[]>([]),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const [j,p]=await Promise.all([s.from("jobs").select("id,status,quoted_amount").eq("consumer_id",user.id).eq("status","accepted").order("created_at",{ascending:false}),s.from("payments").select("id,amount,status,mpesa_receipt,result_desc").eq("payer_id",user.id).order("created_at",{ascending:false}).limit(30)]);setJobs((j.data||[]) as Job[]);setPayments((p.data||[]) as Payment[]);}
 useEffect(()=>{void load()},[]);
 async function pay(job:Job){setBusy(true);setMessage("");try{const phone254=normalizeKenyanPhone(phone);const r=await fetch("/api/payments/mpesa/stk",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId:job.id,amount:job.quoted_amount,phone:phone254})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Payment could not be started.");setMessage(d.message||"M-Pesa prompt sent. Complete it on your phone.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Payment failed")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#141B1F] px-4 py-6 text-white"><div className="mx-auto max-w-lg"><Link href="/consumer" className="text-sm font-bold text-[#F5C451]">← Back to SAVIS</Link><section className="mt-5 overflow-hidden rounded-[28px] border border-[#E22227]/25 bg-gradient-to-br from-[#430000] via-[#7A0003] to-[#222B31] p-6"><div className="flex min-h-40 flex-col items-center justify-center text-center"><div className="text-5xl font-black tracking-[-0.08em] text-white sm:text-6xl">M-PESA</div><div className="mt-2 rounded-full bg-white/10 px-3 py-1 text-[0.65rem] font-black uppercase tracking-[0.22em] text-[#F5C451]">Pay securely in Kenya</div><p className="mt-4 max-w-sm text-xs leading-relaxed text-white/75">SAVIS is prepared for Safaricom M-Pesa payments. Live Safaricom credentials and payment activation can be configured when you are ready.</p></div></section><h1 className="mt-6 text-3xl font-black">Messages & Payments</h1><p className="mt-2 text-sm text-[#B9C3C9]">Pay an accepted protected job through M-Pesa. SAVIS marks the ledger held only after Safaricom confirms the callback.</p><section className="mt-6 rounded-[24px] border border-white/10 bg-[#222B31] p-5"><label className="text-xs font-bold text-[#B9C3C9]">M-Pesa number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0712345678" className="mt-2 w-full rounded-2xl bg-white p-3 text-[#222B31] outline-none"/>{message&&<p className="mt-3 rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-[#F5C451]">{message}</p>}<div className="mt-5 space-y-3">{jobs.length?jobs.map(job=><div key={job.id} className="rounded-2xl border border-white/10 p-4"><div className="flex justify-between"><span className="text-sm font-bold">Protected job</span><b>KES {Number(job.quoted_amount||0).toLocaleString()}</b></div><button disabled={busy||!job.quoted_amount} onClick={()=>void pay(job)} className="mt-3 w-full rounded-xl bg-[#E22227] px-4 py-3 text-sm font-black disabled:opacity-50">{busy?"Starting M-Pesa…":"Pay with M-Pesa"}</button></div>):<p className="text-sm text-[#B9C3C9]">No accepted jobs are waiting for payment.</p>}</div></section><section className="mt-5 rounded-[24px] border border-white/10 bg-[#222B31] p-5"><h2 className="font-extrabold">Payment history</h2><div className="mt-3 space-y-2">{payments.map(p=><div key={p.id} className="rounded-xl bg-white/5 p-3 text-sm"><div className="flex justify-between"><span>KES {Number(p.amount).toLocaleString()}</span><span className="font-bold">{p.status}</span></div>{p.mpesa_receipt&&<p className="mt-1 text-xs text-[#B9C3C9]">Receipt: {p.mpesa_receipt}</p>}{p.result_desc&&p.status==="failed"&&<p className="mt-1 text-xs text-[#FB7185]">{p.result_desc}</p>}</div>)}{!payments.length&&<p className="text-sm text-[#B9C3C9]">No payments yet.</p>}</div></section></div></main>
}