"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";

type Account={id:string;full_name:string|null;email:string|null;phone:string|null;role:string;avatar_url:string|null;service_category:string|null;hourly_rate:number|null;rating:number|null;review_count:number|null;availability:string|null;verified:boolean|null;verification_status:string|null;bio:string|null;location_name:string|null;service_area_km:number|null;created_at:string};

export default function BusinessControlCenter(){
 const supabase=useMemo(()=>createClient(),[]); const [allowed,setAllowed]=useState<boolean|null>(null); const [accounts,setAccounts]=useState<Account[]>([]); const [selected,setSelected]=useState<Account|null>(null); const [search,setSearch]=useState(""); const [role,setRole]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function load(){const {data}=await supabase.rpc("list_developer_business_accounts",{p_search:search||null,p_role:role||null});setAccounts((data||[]) as Account[]);}
 useEffect(()=>{void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login?next=/dev-console-9f3k/business";return;}const {data}=await supabase.rpc("is_developer_admin");setAllowed(Boolean(data));if(data)await load();})();},[supabase]);
 async function save(){if(!selected)return;setBusy(true);setMessage("");const {data,error}=await supabase.rpc("update_developer_business_account",{p_user_id:selected.id,p_full_name:selected.full_name,p_service_category:selected.service_category,p_bio:selected.bio,p_hourly_rate:selected.hourly_rate,p_availability:selected.availability,p_location_name:selected.location_name,p_service_area_km:selected.service_area_km,p_avatar_url:selected.avatar_url});setBusy(false);if(error){setMessage(error.message);return;}setSelected(data as Account);setMessage("Business profile saved and audited.");await load();}
 async function prepareSession(){if(!selected)return;setBusy(true);setMessage("");const {data,error}=await supabase.rpc("prepare_developer_assisted_session",{p_target_user_id:selected.id,p_minutes:30});setBusy(false);if(error){setMessage(error.message);return;}setMessage(`Assisted session prepared until ${new Date(data.expires_at).toLocaleString()}. Owner passwords are never requested or exposed.`);}
 if(allowed===null)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white">Checking developer access…</main>;
 if(!allowed)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white"><div className="rounded-3xl border border-red-400/20 bg-white/[.04] p-8 text-center"><h1 className="text-2xl font-black">Developer access denied</h1><Link href="/dev-console-9f3k" className="mt-5 inline-flex rounded-full bg-white px-5 py-2 text-sm font-bold text-black">Back</Link></div></main>;
 const field=(key:keyof Account,label:string)=><label className="block text-xs font-bold text-white/50">{label}<input value={(selected as any)?.[key]??""} onChange={e=>selected&&setSelected({...selected,[key]:key==="hourly_rate"||key==="service_area_km"?(e.target.value?Number(e.target.value):null):e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white outline-none"/></label>;
 return <main className="min-h-screen bg-[#07050d] text-white"><header className="sticky top-0 z-20 border-b border-violet-400/15 bg-[#0b0714]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><div><p className="text-[11px] font-black uppercase tracking-[.25em] text-[#F5C451]">SAVIS Developer Control Plane</p><h1 className="text-2xl font-black">Business Control Center</h1></div><Link href="/dev-console-9f3k" className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">← Console</Link></div></header>
 <div className="mx-auto max-w-7xl px-4 py-6"><div className="rounded-3xl border border-violet-400/15 bg-violet-400/[.04] p-5"><p className="text-xs font-black uppercase tracking-[.18em] text-violet-200">Business-only management</p><p className="mt-2 text-sm text-white/55">Providers, professional accounts and sellers only. Consumer accounts are intentionally excluded. Every write is audited.</p></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_390px]"><section className="rounded-3xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load()}} placeholder="Search name, email or category" className="min-w-[220px] flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none"/><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"><option value="">All business roles</option><option value="provider">Provider</option><option value="professional">Professional</option><option value="seller">Seller</option></select><button onClick={()=>void load()} className="rounded-xl bg-[#F5C451] px-4 py-2 text-sm font-black text-black">Search</button></div><div className="mt-5 space-y-2">{accounts.length===0?<p className="rounded-2xl border border-white/10 p-5 text-sm text-white/45">No eligible business accounts found.</p>:accounts.map(a=><button key={a.id} onClick={()=>setSelected(a)} className={`w-full rounded-2xl border p-4 text-left ${selected?.id===a.id?"border-violet-300/40 bg-violet-300/10":"border-white/8 bg-black/10 hover:bg-white/[.04]"}`}><div className="flex items-center justify-between gap-3"><div><p className="font-black">{a.full_name||"Unnamed business"}</p><p className="text-xs text-white/45">{a.role} · {a.service_category||"No category"} · {a.email||"No email"}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${a.verified?"bg-emerald-400/15 text-emerald-300":"bg-amber-400/15 text-amber-300"}`}>{a.verified?"VERIFIED":(a.verification_status||"UNVERIFIED").toUpperCase()}</span></div></button>)}</div></section>
 <section className="rounded-3xl border border-white/10 bg-white/[.035] p-5">{!selected?<div className="py-12 text-center text-sm text-white/40">Select a business account to manage it.</div>:<div><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-violet-200">{selected.role}</p><h2 className="text-xl font-black">{selected.full_name||"Unnamed"}</h2></div><span className="text-xs text-white/40">{selected.rating||0} ★ · {selected.review_count||0} reviews</span></div><div className="mt-4 space-y-3">{field("full_name","Business / display name")}{field("service_category","Category")}{field("location_name","Location")}{field("availability","Availability")}{field("hourly_rate","Starting rate (KES)")}{field("service_area_km","Service area (km)")}{field("avatar_url","Avatar / logo URL")}{field("bio","Bio / highlights")}</div>{message&&<p className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-3 text-xs text-white/65">{message}</p>}<div className="mt-4 grid gap-2"><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-violet-500 px-4 py-3 text-sm font-black">Save business profile</button><button disabled={busy} onClick={()=>void prepareSession()} className="rounded-xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm font-black text-amber-200">Prepare 30-min Developer Assisted Session</button></div><p className="mt-3 text-[11px] leading-5 text-white/35">The assisted-session record is time-boxed and audited. It does not expose or require the owner password; full authenticated session handoff will be added on top of this control-plane foundation.</p></div>}</section></div></div></main>;
}
